name: Guto Framework
encoding: UTF-8
markdown: redcarpet
pygments: true
safe: false
relative_permalinks: false

safe:        false
watch:       false    # deprecated
server:      false    # deprecated
host:        0.0.0.0
port:        4001
baseurl:     /
lsi:         false